config/routes.rb
Rails.application.routes.draw do
  get   'settings', to: 'settings#index'
  put   'settings', to: 'settings#update'
  patch 'settings', to: 'settings#update'

  resources :links

  root 'links#index'
end

app/models/link.rb
class Link < ActiveRecord::Base
  # One link can have multiple tags
  has_and_belongs_to_many :tags

  # Sort by `updated_at` DESC when retrieving all links
  default_scope { order(updated_at: :desc) }

  # URL is the only required field
  validates :url, presence: true

  # Default values after initialization
  after_initialize :init

  def init
    # TODO put `is_private?` default value in settings
    self.is_private = false if self.is_private.nil?
  end
end

app/models/settings.rb
class Settings < ActiveRecord::Base
end

app/models/tag.rb
class Tag < ActiveRecord::Base
  has_and_belongs_to_many :links
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :count_links
  before_action :retrieve_settings

  private

  # Used in the site header
  def count_links
    @links_count = Link.count
  end

  def retrieve_settings
    # TODO change for the account ID
    @settings = Settings.find(1)
  end
end

app/controllers/links_controller.rb
class LinksController < ApplicationController
  before_action :set_link, only: [:show, :edit, :update, :destroy]

  def index
    @links = Link.all

    respond_to do |format|
      format.html
      format.atom
    end
  end

  def show
  end

  def new
    @link = Link.new
  end

  def edit
  end

  def create
    @link = Link.new(link_params)

    respond_to do |format|
      if @link.save
        format.html { redirect_to links_path, notice: 'Link was successfully created.' }
        format.json { render :show, status: :created, location: @link }
      else
        format.html { render :new }
        format.json { render json: @link.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @link.update(link_params)
        format.html { redirect_to @link, notice: 'Link was successfully updated.' }
        format.json { render :show, status: :ok, location: @link }
      else
        format.html { render :edit }
        format.json { render json: @link.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @link.destroy
    respond_to do |format|
      format.html { redirect_to links_url, notice: 'Link was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  def set_link
    @link = Link.find(params[:id])
  end

  def link_params
    params.require(:link).permit(:url, :title, :description, :is_private?)
  end
end

app/controllers/settings_controller.rb
class SettingsController < ApplicationController
  def index
  end

  def update
    respond_to do |format|
      if @settings.update(settings_params)
        format.html { redirect_to settings_path, notice: 'Settings successfully updated.' }
        format.json { render :index, status: :ok }
      else
        format.html { render :index }
        format.json { render json: @settings.errors, status: :unprocessable_entity }
      end
    end
  end

  private

  def settings_params
    params.require(:settings).permit(:default_private_link, :page_title, :time_zone)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/links_helper.rb
module LinksHelper
end

app/helpers/settings_helper.rb
module SettingsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Rhaarli</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="header">
  <h1 class="header-title"><%= link_to 'Rhaarli', root_path %></h1>

  <div class="header-description">
    <%= @settings.page_title %>
  </div>

  <ul class="nav" role="nav">
    <li><%= link_to 'Home', root_path %></li>
    <li><%= link_to 'Settings', settings_path %></li>
    <li><%= link_to 'Add Link', new_link_path %></li>
    <li><%= link_to 'RSS Feed', root_path %></li>
    <li><%= link_to 'ATOM Feed', links_path(format: :atom) %></li>
    <li><%= link_to 'Tag Cloud', root_path %></li>
  </ul>

  <div class="header-counter">
    Shaare your links... <%= pluralize @links_count, 'link' %>
  </div>
</div>

<%= yield %>

</body>
</html>

app/views/links/_form.html.erb
<%= form_for @link  do |f| %>
  <% if @link.errors.any? %>
    <div id="error_explanation">
      <h3>
        <%= pluralize(@link.errors.count, 'error') %> prohibited this link from being saved:
      </h3>

      <ul>
        <% @link.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :url %><br>
    <%= f.url_field :url %>
  </div>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>

  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>

  <div class="field">
    <%= f.label :private %><br>
    <%= f.check_box :is_private? %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/links/_link.html.erb
<div class="link">
  <h3 class="link-title"><%= link_to link.title, link.url %></h3>

  <ul class="link-actions">
    <li><%= link_to 'Edit', edit_link_path(link) %></li>
    <li><%= link_to 'Destroy', link, method: :delete, data: { confirm: 'Are you sure?' } %></li>
  </ul>

  <div class="link-description">
    <%= link.description %>
  </div>

  <div class="link-meta">
    <span class="link-date"><%= link.updated_at %></span>
    &blacksquare;
    <%= link_to 'permalink', link_path(link) %>
    &blacksquare;
    <span class="link-permalink"><%= link.url %></span>
  </div>

  <ul class="link-tags">
    <% link.tags.each do |tag| %>
      <li><%= link_to tag.name, '#' %></li>
    <% end %>
  </ul>
</div>

app/views/links/edit.html.erb
<%= render 'form' %>

<%= link_to 'Back', links_path %>

app/views/links/index.html.erb
<p id="notice"><%= notice %></p>

<% @links.each do |link| %>
  <%= render partial: 'link', object: link %>
<% end %>

app/views/links/new.html.erb
<%= render 'form' %>

<%= link_to 'Back', links_path %>

app/views/links/show.html.erb
<p id="notice"><%= notice %></p>

<%= render partial: 'link', object: @link %>

<%= link_to 'Back', links_path %>

app/views/settings/index.html.erb
<p id="notice"><%= notice %></p>

<%= form_for @settings, url: { action: 'update' } do |f| %>
  <% if @settings.errors.any? %>
    <div id="error_explanation">
      <h3>
        <%= pluralize(@settings.errors.count, 'error') %> prohibited the settings from being saved:
      </h3>

      <ul>
        <% @settings.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :page_title %><br>
    <%= f.text_field :page_title %>
  </div>

  <div class="field">
    <%= f.label :time_zone %><br>
    <%= f.time_zone_select :time_zone, /US/ %>
  </div>

  <div class="field">
    <%= f.label :default_private_link %><br>
    <%= f.check_box :default_private_link %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>